x=(input("Enter the three number:"))
y=x.split()
z=list(y)
p=int(z[0])
q=int(z[1])
r=int(z[2])
if p>=q and p>=r: print(p," is the greatest number among",p,",",q,"and",r)
elif q>=p and q>=r: print(q," is the greatest number among",p,",",y,"and",z)
else:print(r," is the greatest number among",p,",",q,"and",r)
